# -*- coding: utf-8 -*-
"""databaseTester.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IxnDPdQjuzULWTMl22VBjXsoecb9BJXx
"""

import sqlite3

#Connection
connection = sqlite3.connect("CleverCart.db")

#Cursor to point at what is being done and executed
cursor = connection.cursor()

#Creating an ingredient table
cursor.execute(""" CREATE TABLE IF NOT EXISTS ingredients (name_ingred TEXT,
price FLOAT, weight FLOAT); """)

#Inserting into the table
cursor.execute(""" INSERT INTO ingredients (name_ingred, price, weight) VALUES ('Bread', 6.79, 1.2),('Spagetti Sauce', 3.25, 1.06),('Cheese', 4.56, 2.45); """)

#tester select statement
cursor.execute(""" SELECT name_ingred FROM ingredients WHERE price == 6.79; """)

#print statement
print(cursor.fetchall())

#Closing connection
connection.close()