# -*- coding: utf-8 -*-
"""DatabaseUpdated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bn4ThRB_1mAG71lLJCXPWfl_Dj3oxouk
"""

import sqlite3

#Connection
connection = sqlite3.connect("CleverCart.db")

#Cursor to point at what is being done and executed
cursor = connection.cursor()

#Creating an ingredient table
cursor.execute(""" CREATE TABLE IF NOT EXISTS Product (product varchar(255),
price DOUBLE(5, 2), store varchar(64)) """)

def cache_item(search_term, price, store):
    cursor.execute("IF NOT EXISTS SELECT product FROM Product WHERE product = ?", (search_term))
    if cursor.fetchone() is None:
        cursor.execute("INSERT INTO Product (product, price, store) VALUES (?, ?, ?)", (search_term, price, store))

def search_byProduct(search_term):
    cursor.execute("SELECT * FROM Product WHERE product = ?", (search_term))
    return cursor.fetchall()

def search_byPrice(price):
    cursor.execute("SELECT * FROM Product WHERE price = ?", (price))
    return cursor.fetchall()

def search_byStore(store):
    cursor.execute("SELECT * FROM Product WHERE store = ?", (store))
    return cursor.fetchall()

