# -*- coding: utf-8 -*-
"""DatabaseFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3SDMsXgvGOO6eUa0OQfSWk6g7QTjGea
"""

import sqlite3

#Connection
connection = sqlite3.connect("CleverCart.db")

#Cursor to point at what is being done and executed
cursor = connection.cursor()

#Creating an ingredient table
cursor.execute(""" CREATE TABLE IF NOT EXISTS Product (search_term varchar(255), product varchar(255),
price DOUBLE(5, 2), store varchar(64)) """)

def cache_item(search_term, product, price, store):
    cursor.execute("SELECT product FROM Product WHERE search_term = ? AND product = ? AND store = ?", (search_term, product, store))
    if cursor.fetchone() is None:
        cursor.execute("INSERT INTO Product (search_term, product, price, store) VALUES (?, ?, ?, ?)", (search_term, product, price, store))
    else:
        cursor.execute("UPDATE Product SET price = ? WHERE search_term = ? AND product = ? AND store = ?", (price, search_term, product, store))
    connection.commit()

def fetch_items(search_term, store):
    cursor.execute("SELECT product, price, store FROM Product WHERE search_term = ? AND store = ?", (search_term, store))
    return cursor.fetchall()